### ISSUE TITLE
About data collection

### ISSUE THREAD

**Issue by SmashChen** [autonomousvision/carla_garage#23]
Hi, authors. Thanks for your great work!
I want to collection data by using [generate_dataset_slurm.py](https://github.com/autonomousvision/carla_garage/blob/main/generate_dataset_slurm.py) script. After I modified "code_root" and "carla_root" I ran the script but it raised an error:

Starting to generate data
Number of jobs: 210
0/5 jobs are running...
Submitting job 0/210: /home/chenzesong/CarlaDataset/hb_dataset_v08_2023_05_10_logs/run_files/job_files/0.sh
/bin/sh: 1: squeue: not found
/bin/sh: 1: sbatch: not found
Traceback (most recent call last):
  File "/home/chenzesong/Carla_test/Longest6_2023/carla_garage/generate_dataset_slurm.py", line 375, in <module>
    main()
  File "/home/chenzesong/Carla_test/Longest6_2023/carla_garage/generate_dataset_slurm.py", line 303, in main
    jobid = subprocess.check_output(f'sbatch {job_file}', shell=True).decode('utf-8').strip().rsplit(' ', maxsplit=1)[-1]
  File "/home/chenzesong/anaconda3/envs/pytorch/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/chenzesong/anaconda3/envs/pytorch/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sbatch /home/chenzesong/CarlaDataset/hb_dataset_v08_2023_05_10_logs/run_files/job_files/0.sh' returned non-zero exit status 127.

I've tried looking for a solution but haven't been able to so far, can you give me some advice? Thank you very much!

**Comment by HenryZhangJianhe** [comment]
how did you solve this problem?
